name: Terraform CI

on:
  workflow_dispatch:   # запуск вручную из UI
  push:
    branches: [ main ] # автоматически при пуше в main

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: "1.12.2"

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan \
          -var="access_key=${{ secrets.TF_ACCESS_KEY }}" \
          -var="secret_key=${{ secrets.TF_SECRET_KEY }}"

      - name: Terraform Apply
        if: github.ref == 'refs/heads/main'
        run: terraform apply -auto-approve \
          -var="access_key=${{ secrets.TF_ACCESS_KEY }}" \
          -var="secret_key=${{ secrets.TF_SECRET_KEY }}"

